# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-04-18T13:06:05+00:00

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, NaiveDatetime


class Bundesland(Enum):
    Burgenland = "Burgenland"
    Kärnten = "Kärnten"
    Niederösterreich = "Niederösterreich"
    Oberösterreich = "Oberösterreich"
    Salzburg = "Salzburg"
    Steiermark = "Steiermark"
    Tirol = "Tirol"
    Vorarlberg = "Vorarlberg"
    Wien = "Wien"


class CodeListItem(BaseModel):
    key: int | None = Field(..., title="Key")
    value: str = Field(..., title="Value")


class EndpointMode(Enum):
    historical = "historical"
    current = "current"
    forecast = "forecast"


class EndpointType(Enum):
    grid = "grid"
    timeseries = "timeseries"
    station = "station"


class FrequencyStep(BaseModel):
    from_index: int = Field(..., examples=[0], title="From Index")
    to_index: int = Field(..., examples=[16], title="To Index")
    frequency: str = Field(..., examples=["0D3600S"], title="Frequency")
    step_offset: str = Field(
        ..., description="", examples=["P0DT0H0M0S"], title="Step Offset"
    )


class GeoJSONFeatureParameter(BaseModel):
    name: str = Field(..., examples=["RR"], title="Name")
    unit: str = Field(..., examples=["kg m-2"], title="Unit")
    data: list[float | None] = Field(..., examples=[[9.0, 0.0]], title="Data")


class GeoJSONFeatureProperties(BaseModel):
    parameters: dict[str, GeoJSONFeatureParameter] = Field(..., title="Parameters")


class GeoJSONPoint(BaseModel):
    type: Literal["Point"] = Field("Point", title="Type")
    coordinates: list[float] = Field(
        ...,
        description="Point coordinates are in x, y order (easting, northing for projected coordinates, longitude, and latitude for geographic coordinates)",
        examples=[[16.356388092041016, 48.24861145019531]],
        max_length=2,
        min_length=2,
        title="Coordinates",
    )


class IdType(Enum):
    Synop = "Synop"
    Klima = "Klima"


class MDType(Enum):
    stations = "stations"
    parameters = "parameters"


class OutputFormat(Enum):
    geojson = "geojson"
    netcdf = "netcdf"
    csv = "csv"


class ParameterMetadataModel(BaseModel):
    name: str = Field(..., examples=["RR"], title="Name")
    long_name: str = Field(
        ..., examples=["1-hour precipitation sum"], title="Long Name"
    )
    description: str = Field(
        ..., examples=["1-hour precipitation sum"], title="Description"
    )
    unit: str = Field(..., examples=["kg m-2"], title="Unit")
    code_list_ref: str | None = Field(
        None, examples=[None, "c01"], title="Code List Ref"
    )


class StationFilterEndpointMode(Enum):
    historical = "historical"
    current = "current"


class StationGeoJSONProperties(BaseModel):
    parameters: dict[str, GeoJSONFeatureParameter] = Field(..., title="Parameters")
    station: str = Field(..., title="Station")


class StationMetadataType(Enum):
    COMBINED = "COMBINED"
    SUB_STATION = "SUB_STATION"
    INDIVIDUAL = "INDIVIDUAL"


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class Dataset(BaseModel):
    type: EndpointType
    mode: EndpointMode
    response_formats: list[OutputFormat] = Field(..., title="Response Formats")
    url: str = Field(..., title="Url")


class GeoJSONFeature(BaseModel):
    type: Literal["Feature"] = Field("Feature", title="Type")
    geometry: GeoJSONPoint
    properties: GeoJSONFeatureProperties


class GridForecastGeoJSONSerializer(BaseModel):
    reference_time: AwareDatetime = Field(..., title="Reference Time")
    media_type: Literal["application/json"] = Field(
        "application/json", title="Media Type"
    )
    type: Literal["FeatureCollection"] = Field("FeatureCollection", title="Type")
    version: str = Field(..., title="Version")
    timestamps: list[AwareDatetime] = Field(
        ..., description="Format: *YYYY-MM-DDThh:mm:ss±hh:mm*", title="Timestamps"
    )
    features: list[GeoJSONFeature] = Field(..., title="Features")
    filename: str | None = Field("Filename", title="Filename")
    bbox: list[float] = Field(..., max_length=4, min_length=4, title="Bbox")


class GridForecastMetadataModel(BaseModel):
    title: str = Field(..., title="Title")
    parameters: list[ParameterMetadataModel] = Field(..., title="Parameters")
    frequency: list[FrequencyStep] | str = Field(..., title="Frequency")
    type: str = Field(..., title="Type")
    mode: str = Field(..., title="Mode")
    response_formats: list[str] = Field(
        ..., examples=[["geojson", "netcdf"]], title="Response Formats"
    )
    code_lists: dict[str, list[CodeListItem]] | None = Field(
        None,
        examples=[{"c1": [{"key": 0, "value": "Niederschlag gemessen"}]}],
        title="Code Lists",
    )
    last_forecast_reftime: AwareDatetime | None = Field(
        None, title="Last Forecast Reftime"
    )
    max_forecast_offset: int | None = Field(None, title="Max Forecast Offset")
    available_forecast_reftimes: list[AwareDatetime] = Field(
        ..., title="Available Forecast Reftimes"
    )
    forecast_length: int | None = Field(None, title="Forecast Length")
    bbox: list[float] = Field(..., max_length=4, min_length=4, title="Bbox")
    bbox_outer: list[float] = Field(..., max_length=4, min_length=4, title="Bbox Outer")
    spatial_resolution: int | float | list[int | float] = Field(
        ..., examples=[1000, 0.28, [0.28, 0.09]], title="Spatial Resolution"
    )
    spatial_resolution_m: int = Field(
        ..., description="deprecated", examples=[1000], title="Spatial Resolution M"
    )
    spatial_resolution_unit: str = Field(
        ..., examples=["m", "deg"], title="Spatial Resolution Unit"
    )
    crs: str = Field(..., examples=["EPSG:4326"], title="Crs")
    grid_bounds: list[float] = Field(
        ..., max_length=4, min_length=4, title="Grid Bounds"
    )


class GridGeoJSONSerializer(BaseModel):
    media_type: Literal["application/json"] = Field(
        "application/json", title="Media Type"
    )
    type: Literal["FeatureCollection"] = Field("FeatureCollection", title="Type")
    version: str = Field(..., title="Version")
    timestamps: list[AwareDatetime] = Field(
        ..., description="Format: *YYYY-MM-DDThh:mm:ss±hh:mm*", title="Timestamps"
    )
    features: list[GeoJSONFeature] = Field(..., title="Features")
    filename: str | None = Field("Filename", title="Filename")
    bbox: list[float] = Field(..., max_length=4, min_length=4, title="Bbox")


class GridHistoricalMetadataModel(BaseModel):
    title: str = Field(..., title="Title")
    parameters: list[ParameterMetadataModel] = Field(..., title="Parameters")
    frequency: list[FrequencyStep] | str = Field(..., title="Frequency")
    type: str = Field(..., title="Type")
    mode: str = Field(..., title="Mode")
    response_formats: list[str] = Field(
        ..., examples=[["geojson", "netcdf"]], title="Response Formats"
    )
    code_lists: dict[str, list[CodeListItem]] | None = Field(
        None,
        examples=[{"c1": [{"key": 0, "value": "Niederschlag gemessen"}]}],
        title="Code Lists",
    )
    start_time: AwareDatetime = Field(..., title="Start Time")
    end_time: AwareDatetime = Field(..., title="End Time")
    bbox: list[float] = Field(..., max_length=4, min_length=4, title="Bbox")
    bbox_outer: list[float] = Field(..., max_length=4, min_length=4, title="Bbox Outer")
    spatial_resolution: int | float | list[int | float] = Field(
        ..., examples=[1000, 0.28, [0.28, 0.09]], title="Spatial Resolution"
    )
    spatial_resolution_m: int = Field(
        ..., description="deprecated", examples=[1000], title="Spatial Resolution M"
    )
    spatial_resolution_unit: str = Field(
        ..., examples=["m", "deg"], title="Spatial Resolution Unit"
    )
    crs: str = Field(..., examples=["EPSG:4326"], title="Crs")
    grid_bounds: list[float] = Field(
        ..., max_length=4, min_length=4, title="Grid Bounds"
    )


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title="Detail")


class StationGeoJSONFeature(BaseModel):
    type: Literal["Feature"] = Field("Feature", title="Type")
    geometry: GeoJSONPoint
    properties: StationGeoJSONProperties


class StationGeoJSONSerializer(BaseModel):
    media_type: Literal["application/json"] = Field(
        "application/json", title="Media Type"
    )
    type: Literal["FeatureCollection"] = Field("FeatureCollection", title="Type")
    version: str = Field(..., title="Version")
    timestamps: list[AwareDatetime] = Field(
        ..., description="Format: *YYYY-MM-DDThh:mm:ss±hh:mm*", title="Timestamps"
    )
    features: list[StationGeoJSONFeature] = Field(..., title="Features")
    filename: str | None = Field("Filename", title="Filename")


class StationMetadata(BaseModel):
    type: StationMetadataType = Field(..., examples=["INDIVIDUAL"])
    id: int = Field(..., examples=[5904], title="Id")
    group_id: int | None = Field(None, examples=[105], title="Group Id")
    name: str = Field(..., examples=["WIEN-HOHE WARTE"], title="Name")
    state: Bundesland | None = Field(None, examples=["Wien"])
    lat: float = Field(..., examples=[48.248611], title="Lat")
    lon: float = Field(..., examples=[16.356388], title="Lon")
    altitude: float | None = Field(None, examples=[198.0], title="Altitude")
    valid_from: AwareDatetime = Field(
        ..., examples=["1992-11-05T00:00:00"], title="Valid From"
    )
    valid_to: AwareDatetime = Field(
        ..., examples=["2100-12-31T00:00:00"], title="Valid To"
    )
    has_sunshine: bool | None = Field(None, examples=[True], title="Has Sunshine")
    has_global_radiation: bool | None = Field(
        None, examples=[True], title="Has Global Radiation"
    )
    is_active: bool | None = Field(None, examples=[True], title="Is Active")


class StationMetadataDto(BaseModel):
    type: StationMetadataType
    id: str = Field(..., title="Id")
    name: str = Field(..., title="Name")
    state: Bundesland | None = None
    lat: float = Field(..., title="Lat")
    lon: float = Field(..., title="Lon")
    altitude: float | None = Field(None, title="Altitude")
    valid_from: AwareDatetime = Field(..., title="Valid From")
    valid_to: AwareDatetime = Field(..., title="Valid To")
    has_sunshine: bool | None = Field(None, title="Has Sunshine")
    has_global_radiation: bool | None = Field(None, title="Has Global Radiation")
    is_active: bool | None = Field(None, title="Is Active")
    sub_stations: list[StationMetadataDto] | None = Field(
        [],
        description="List of sub-stations of this station. Only populated if type == COMBINED.",
        title="Sub Stations",
        validate_default=True,
    )
    matches: bool | None = Field(True, title="Matches")


class TimeseriesForecastGeoJSONSerializer(BaseModel):
    reference_time: AwareDatetime = Field(..., title="Reference Time")
    media_type: Literal["application/json"] = Field(
        "application/json", title="Media Type"
    )
    type: Literal["FeatureCollection"] = Field("FeatureCollection", title="Type")
    version: str = Field(..., title="Version")
    timestamps: list[AwareDatetime] = Field(
        ..., description="Format: *YYYY-MM-DDThh:mm:ss±hh:mm*", title="Timestamps"
    )
    features: list[GeoJSONFeature] = Field(..., title="Features")
    filename: str | None = Field("Filename", title="Filename")


class TimeseriesGeoJSONSerializer(BaseModel):
    media_type: Literal["application/json"] = Field(
        "application/json", title="Media Type"
    )
    type: Literal["FeatureCollection"] = Field("FeatureCollection", title="Type")
    version: str = Field(..., title="Version")
    timestamps: list[AwareDatetime] = Field(
        ..., description="Format: *YYYY-MM-DDThh:mm:ss±hh:mm*", title="Timestamps"
    )
    features: list[GeoJSONFeature] = Field(..., title="Features")
    filename: str | None = Field("Filename", title="Filename")


class StationCurrentMetadataModel(BaseModel):
    title: str = Field(..., title="Title")
    parameters: list[ParameterMetadataModel] = Field(..., title="Parameters")
    frequency: list[FrequencyStep] | str = Field(..., title="Frequency")
    type: str = Field(..., title="Type")
    mode: str = Field(..., title="Mode")
    response_formats: list[str] = Field(
        ..., examples=[["geojson", "netcdf"]], title="Response Formats"
    )
    code_lists: dict[str, list[CodeListItem]] | None = Field(
        None,
        examples=[{"c1": [{"key": 0, "value": "Niederschlag gemessen"}]}],
        title="Code Lists",
    )
    time: AwareDatetime = Field(..., title="Time")
    stations: list[StationMetadata] = Field(..., title="Stations")
    id_type: IdType


class StationFilterResponseDto(BaseModel):
    num_stations_total: int = Field(..., title="Num Stations Total")
    num_stations_matching: int = Field(..., title="Num Stations Matching")
    matching_stations: list[StationMetadataDto] = Field(..., title="Matching Stations")


class StationHistoricalMetadataModel(BaseModel):
    title: str = Field(..., title="Title")
    parameters: list[ParameterMetadataModel] = Field(..., title="Parameters")
    frequency: list[FrequencyStep] | str = Field(..., title="Frequency")
    type: str = Field(..., title="Type")
    mode: str = Field(..., title="Mode")
    response_formats: list[str] = Field(
        ..., examples=[["geojson", "netcdf"]], title="Response Formats"
    )
    code_lists: dict[str, list[CodeListItem]] | None = Field(
        None,
        examples=[{"c1": [{"key": 0, "value": "Niederschlag gemessen"}]}],
        title="Code Lists",
    )
    start_time: AwareDatetime = Field(..., title="Start Time")
    end_time: NaiveDatetime = Field(..., title="End Time")
    stations: list[StationMetadata] = Field(..., title="Stations")
    id_type: IdType


StationMetadataDto.model_rebuild()
